services:
  - type: web
    name: talentifyfaceapi
    env: python
    plan: free
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --workers=2 --threads=4 --timeout 300 --bind 0.0.0.0:$PORT app:app
    envVars:
      PYTHON_VERSION: 3.10.13
