services:
  - type: web
    name: talentifyfaceapi
    env: python
    region: oregon
    plan: free

    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt

    startCommand: gunicorn --workers=2 --threads=4 --timeout 300 --bind 0.0.0.0:$PORT app:app

    envVars:
      PYTHON_VERSION: 3.10.13
      DEEPFACE_HOME: /tmp/deepface
      TF_CPP_MIN_LOG_LEVEL: 3
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      PYTHONUNBUFFERED: 1
      DISABLE_DEEPFACE_ANALYZER: 1
