services:
  - type: web
    name: talentify-face-api
    runtime: python
    repo: https://github.com/your-username/talentify-face-api
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    region: oregon
    autoDeploy: true

    envVars:
      PYTHON_VERSION: 3.10.13
      DEEPFACE_HOME: /tmp/deepface
      TF_CPP_MIN_LOG_LEVEL: 3
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      PYTHONUNBUFFERED: 1
      DISABLE_DEEPFACE_ANALYZER: 1
      PORT: 5000
