services:
  - type: web
    name: talentifyfaceapi
    env: python
    plan: free
    region: oregon

    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt

    startCommand: python app.py

    envVars:
      PYTHON_VERSION: 3.10.13
      TF_CPP_MIN_LOG_LEVEL: "2"        # Suppress TensorFlow debug spam
      DEEPFACE_HOME: "/opt/render/.deepface"  # Cache models safely
      PORT: 5000
