services:
  - type: web
    name: talentify-face-api
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 180 --workers 1 --threads 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 3   # Suppress TensorFlow logs
      - key: DEEPFACE_HOME
        value: /opt/render/project/.deepface_cache
